name: Semantic Release Dry Run
on: [workflow_dispatch]
jobs:
  release:
    name: semantic_release_dry_run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Semantic release
      id: semantic
      uses: cycjimmy/semantic-release-action@v2
      with:
        dry_run: true
        extra_plugins: |
          @semantic-release/changelog
          @semantic-release/git
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Output info
      run: |
        echo ${{ steps.semantic.outputs.new_release_published }}
        echo ${{ steps.semantic.outputs.new_release_version }}
